name: Deploy via SSH
on:
  push:
    branches:
      - master
env:
  appid: 'apidev'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copy file from GitHub to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "."
        target: "/home/${{ env.appid }}"
    - name: Run set up commands on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          cd /home/${{ env.appid }}
          npm i
          pm2 stop ${{ env.appid }}; pm2 start index.js  --name '${{ env.appid }}'
          cp *.nginx /etc/nginx/sites-enabled/
          systemctl restart nginx