name: Deploy via SSH
on:
  push:
    branches:
      - master
env:
  testvar: 'Helllooooo'

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Copy file from GitHub to Server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "."
        target: "/home/test"
    - name: Run set up commands on server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: |
          echo "I am ${{ env.testvar }}"
        
# cd /home/api-dev
# npm i
# pm2 stop api-dev; pm2 start index.js  --name 'api-dev'
# cp *.nginx /etc/nginx/sites-enabled/
# systemctl restart nginx