name: Deploy via SSH
on:
  push:
    branches:
      - master
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "."
        target: "/home/test"
    - name: pass environment
      uses: appleboy/ssh-action@master
      env:
        FOO: "BAR"
        BAR: "FOO"
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        envs: FOO,BAR
        script: |
          echo "I am $FOO"
          echo "I am $BAR"
        
# cd /home/api-dev
# npm i
# pm2 stop api-dev; pm2 start index.js  --name 'api-dev'
# cp *.nginx /etc/nginx/sites-enabled/
# systemctl restart nginx